// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Bdd.Specs.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ActorFeature : object, Xunit.IClassFixture<ActorFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Actor.feature"
#line hidden
        
        public ActorFeature(ActorFeature.FixtureData fixtureData, Bdd_Specs_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Actor", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Adding an actor")]
        [Xunit.TraitAttribute("FeatureTitle", "Actor")]
        [Xunit.TraitAttribute("Description", "Adding an actor")]
        [Xunit.TraitAttribute("Category", "addactor")]
        [Xunit.InlineDataAttribute("{ \"name\":\"Anushka\",\"bio\": \"AnushkaBio\",\"dob\": \"2001-12-02T00:00:00\",\"gender\": \"fe" +
            "male\" }", "actors/AddActor", "201", "1", new string[0])]
        [Xunit.InlineDataAttribute("{\"name\":\"\",\"bio\":\"AnushkaBio\",\"dob\":\"2001-12-02T00:00:00\",\"gender\":\"female\"}", "actors/AddActor", "400", "invalid Arguments", new string[0])]
        [Xunit.InlineDataAttribute("{\"name\":\"Anushka\",\"bio\":\"\",\"dob\":\"2001-12-02T00:00:00\",\"gender\":\"female\"}", "actors/AddActor", "400", "invalid Arguments", new string[0])]
        [Xunit.InlineDataAttribute("{\"name\":\"Anushka\",\"bio\":\"AnushkaBio\",\"dob\":\"2001-12-02T00:00:00\",\"gender\":\"\"}", "actors/AddActor", "400", "invalid Arguments", new string[0])]
        public virtual void AddingAnActor(string data, string resourceEndpoint, string statusCode, string responseData, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "addactor"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Data", data);
            argumentsOfScenario.Add("resourceEndpoint", resourceEndpoint);
            argumentsOfScenario.Add("statusCode", statusCode);
            argumentsOfScenario.Add("responseData", responseData);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding an actor", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
    testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 6
    testRunner.When(string.Format("I am making a post request to \'{0}\' with the following Data \'{1}\'", resourceEndpoint, data), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 7
    testRunner.Then(string.Format("response code must be \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 8
    testRunner.And(string.Format("response data must look like \'{0}\'", responseData), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Display the list of Actors")]
        [Xunit.TraitAttribute("FeatureTitle", "Actor")]
        [Xunit.TraitAttribute("Description", "Display the list of Actors")]
        [Xunit.TraitAttribute("Category", "displayactors")]
        [Xunit.InlineDataAttribute("actors/GetAllActors", "200", "[{\"id\":1,\"name\":\"Anushka\",\"bio\":\"AnushkaBio\",\"dob\":\"2001-12-02T00:00:00\",\"gender\"" +
            ":\"female\"},{\"id\":2,\"name\":\"Prabhas\",\"bio\":\"PrabhasBio\",\"dob\":\"2000-08-04T00:00:0" +
            "0\",\"gender\":\"male\"}]", new string[0])]
        public virtual void DisplayTheListOfActors(string resourceEndpoint, string statusCode, string responseData, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "displayactors"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("resourceEndpoint", resourceEndpoint);
            argumentsOfScenario.Add("statusCode", statusCode);
            argumentsOfScenario.Add("responseData", responseData);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Display the list of Actors", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 18
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 19
         testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 20
         testRunner.When(string.Format("I make GET Request \'{0}\'", resourceEndpoint), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 21
         testRunner.Then(string.Format("response code must be \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 22
         testRunner.And(string.Format("response data must look like \'{0}\'", responseData), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Display the actor by using id")]
        [Xunit.TraitAttribute("FeatureTitle", "Actor")]
        [Xunit.TraitAttribute("Description", "Display the actor by using id")]
        [Xunit.TraitAttribute("Category", "displayactor")]
        [Xunit.InlineDataAttribute("actors/GetActorById/1", "200", "{\"id\":1,\"name\":\"Anushka\",\"bio\":\"AnushkaBio\",\"dob\":\"2001-12-02T00:00:00\",\"gender\":" +
            "\"female\"}", new string[0])]
        [Xunit.InlineDataAttribute("actors/GetActorById/100", "404", "No Content Found", new string[0])]
        [Xunit.InlineDataAttribute("actors/GetActorById/-1", "400", "invalid Arguments", new string[0])]
        [Xunit.InlineDataAttribute("actors/GetActorById/0", "400", "invalid Arguments", new string[0])]
        public virtual void DisplayTheActorByUsingId(string resourceEndpoint, string statusCode, string responseData, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "displayactor"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("resourceEndpoint", resourceEndpoint);
            argumentsOfScenario.Add("statusCode", statusCode);
            argumentsOfScenario.Add("responseData", responseData);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Display the actor by using id", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 30
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 31
         testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 32
         testRunner.When(string.Format("I make GET Request using Id \'{0}\'", resourceEndpoint), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 33
         testRunner.Then(string.Format("response code must be \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 34
         testRunner.And(string.Format("response data must look like \'{0}\'", responseData), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Delete the actor using id")]
        [Xunit.TraitAttribute("FeatureTitle", "Actor")]
        [Xunit.TraitAttribute("Description", "Delete the actor using id")]
        [Xunit.TraitAttribute("Category", "deleteactor")]
        [Xunit.InlineDataAttribute("actors/DeleteActor/1", "200", "deleted successfully", new string[0])]
        [Xunit.InlineDataAttribute("actors/DeleteActor/-1", "400", "invalid Arguments", new string[0])]
        [Xunit.InlineDataAttribute("actors/DeleteActor/0", "400", "invalid Arguments", new string[0])]
        [Xunit.InlineDataAttribute("actors/DeleteActor/100", "404", "No Content Found", new string[0])]
        public virtual void DeleteTheActorUsingId(string resourceEndpoint, string statusCode, string responseData, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "deleteactor"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("resourceEndpoint", resourceEndpoint);
            argumentsOfScenario.Add("statusCode", statusCode);
            argumentsOfScenario.Add("responseData", responseData);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete the actor using id", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 44
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 45
         testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 46
         testRunner.When(string.Format("I make Delete Request \'{0}\'", resourceEndpoint), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 47
         testRunner.Then(string.Format("response code must be \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 48
         testRunner.And(string.Format("response data must look like \'{0}\'", responseData), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="update the actor using id")]
        [Xunit.TraitAttribute("FeatureTitle", "Actor")]
        [Xunit.TraitAttribute("Description", "update the actor using id")]
        [Xunit.TraitAttribute("Category", "updateactor")]
        [Xunit.InlineDataAttribute("{\"name\":\"Anushka\",\"bio\": \"AnushkaBio\",\"dob\": \"1989-05-12T15:07:39.346Z\",\"gender\":" +
            " \"female\" }", "actors/UpdateActor/1", "200", "updated successfully", new string[0])]
        [Xunit.InlineDataAttribute("{\"name\":\"\",\"bio\":\"AnushkaBio\",\"dob\":\"1989-05-12T15:07:39.346Z\",\"gender\":\"female\"}" +
            "", "actors/UpdateActor/1", "400", "invalid Arguments", new string[0])]
        [Xunit.InlineDataAttribute("{\"name\":\"Anushka\",\"bio\":\"\",\"dob\":\"1989-05-12T15:07:39.346Z\",\"gender\":\"female\"}", "actors/UpdateActor/1", "400", "invalid Arguments", new string[0])]
        [Xunit.InlineDataAttribute("{\"name\":\"Anushka\",\"bio\":\"AnushkaBio\",\"dob\":\"1989-05-12T15:07:39.346Z\",\"gender\":\"\"" +
            "}", "actors/UpdateActor/1", "400", "invalid Arguments", new string[0])]
        [Xunit.InlineDataAttribute("{\"name\":\"Anushka\",\"bio\":\"AnushkaBio\",\"dob\":\"1989-05-12T15:07:39.346Z\",\"gender\":\"f" +
            "emale\"}", "actors/UpdateActor/-1", "400", "invalid Arguments", new string[0])]
        [Xunit.InlineDataAttribute("{\"name\":\"Anushka\",\"bio\":\"AnushkaBio\",\"dob\":\"1989-05-12T15:07:39.346Z\",\"gender\":\"f" +
            "emale\"}", "actors/UpdateActor/8", "404", "No Content Found", new string[0])]
        public virtual void UpdateTheActorUsingId(string data, string resourceEndpoint, string statusCode, string responseData, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "updateactor"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Data", data);
            argumentsOfScenario.Add("resourceEndpoint", resourceEndpoint);
            argumentsOfScenario.Add("statusCode", statusCode);
            argumentsOfScenario.Add("responseData", responseData);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("update the actor using id", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 60
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 61
          testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 62
          testRunner.When(string.Format("I make PUT Request \'{0}\' with the following Data with the following Data \'{1}\'", resourceEndpoint, data), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 63
          testRunner.Then(string.Format("response code must be \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 64
          testRunner.And(string.Format("response data must look like \'{0}\'", responseData), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ActorFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ActorFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
