// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Bdd.Specs.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ProducerFeature : object, Xunit.IClassFixture<ProducerFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Producer.feature"
#line hidden
        
        public ProducerFeature(ProducerFeature.FixtureData fixtureData, Bdd_Specs_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "producer", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Adding an producer")]
        [Xunit.TraitAttribute("FeatureTitle", "producer")]
        [Xunit.TraitAttribute("Description", "Adding an producer")]
        [Xunit.TraitAttribute("Category", "addproducer")]
        [Xunit.InlineDataAttribute("{ \"name\":\"jerry christopher\",\"bio\": \"JerryBio\",\"dob\": \"2001-12-02T00:00:00\",\"gend" +
            "er\": \"male\" }", "producers/AddProducer", "201", "1", new string[0])]
        [Xunit.InlineDataAttribute("{\"name\":\"\",\"bio\":\"JerryBio\",\"dob\":\"2001-12-02T00:00:00\",\"gender\":\"male\"}", "producers/AddProducer", "400", "invalid Arguments", new string[0])]
        [Xunit.InlineDataAttribute("{\"name\":\"jerry christopher\",\"bio\":\"\",\"dob\":\"2001-12-02T00:00:00\",\"gender\":\"male\"}" +
            "", "producers/AddProducer", "400", "invalid Arguments", new string[0])]
        [Xunit.InlineDataAttribute("{\"name\":\"jerry christopher\",\"bio\":\"JerryBio\",\"dob\":\"2001-12-02T00:00:00\",\"gender\"" +
            ":\"\"}", "producers/AddProducer", "400", "invalid Arguments", new string[0])]
        public virtual void AddingAnProducer(string data, string resourceEndpoint, string statusCode, string responseData, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "addproducer"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Data", data);
            argumentsOfScenario.Add("resourceEndpoint", resourceEndpoint);
            argumentsOfScenario.Add("statusCode", statusCode);
            argumentsOfScenario.Add("responseData", responseData);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Adding an producer", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 4
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
    testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 6
    testRunner.When(string.Format("I am making a post request to \'{0}\' with the following Data \'{1}\'", resourceEndpoint, data), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 7
    testRunner.Then(string.Format("response code must be \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 8
    testRunner.And(string.Format("response data must look like \'{0}\'", responseData), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Display the list of producers")]
        [Xunit.TraitAttribute("FeatureTitle", "producer")]
        [Xunit.TraitAttribute("Description", "Display the list of producers")]
        [Xunit.TraitAttribute("Category", "displayproducers")]
        [Xunit.InlineDataAttribute("producers/GetAllProducers", "200", "[{\"id\":1,\"name\":\"jerry Christopher\",\"bio\":\"jerryBio\",\"dob\":\"2001-12-02T00:00:00\"," +
            "\"gender\":\"male\"},{\"id\":2,\"name\":\"Priyanka\",\"bio\":\"PriyankaBio\",\"dob\":\"1998-06-05" +
            "T00:00:00\",\"gender\":\"female\"}]", new string[0])]
        public virtual void DisplayTheListOfProducers(string resourceEndpoint, string statusCode, string responseData, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "displayproducers"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("resourceEndpoint", resourceEndpoint);
            argumentsOfScenario.Add("statusCode", statusCode);
            argumentsOfScenario.Add("responseData", responseData);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Display the list of producers", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 18
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 19
         testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 20
         testRunner.When(string.Format("I make GET Request \'{0}\'", resourceEndpoint), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 21
         testRunner.Then(string.Format("response code must be \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 22
         testRunner.And(string.Format("response data must look like \'{0}\'", responseData), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Display the producer by using id")]
        [Xunit.TraitAttribute("FeatureTitle", "producer")]
        [Xunit.TraitAttribute("Description", "Display the producer by using id")]
        [Xunit.TraitAttribute("Category", "displayproducer")]
        [Xunit.InlineDataAttribute("producers/GetProducerById/1", "200", "{\"id\":1,\"name\":\"jerry Christopher\",\"bio\":\"jerryBio\",\"dob\":\"2001-12-02T00:00:00\",\"" +
            "gender\":\"male\"}", new string[0])]
        [Xunit.InlineDataAttribute("producers/GetProducerById/100", "404", "No Content Found", new string[0])]
        [Xunit.InlineDataAttribute("producers/GetProducerById/-1", "400", "invalid Arguments", new string[0])]
        [Xunit.InlineDataAttribute("producers/GetProducerById/0", "400", "invalid Arguments", new string[0])]
        public virtual void DisplayTheProducerByUsingId(string resourceEndpoint, string statusCode, string responseData, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "displayproducer"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("resourceEndpoint", resourceEndpoint);
            argumentsOfScenario.Add("statusCode", statusCode);
            argumentsOfScenario.Add("responseData", responseData);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Display the producer by using id", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 29
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 30
         testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 31
         testRunner.When(string.Format("I make GET Request using Id \'{0}\'", resourceEndpoint), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 32
         testRunner.Then(string.Format("response code must be \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 33
         testRunner.And(string.Format("response data must look like \'{0}\'", responseData), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="Delete the producer using id")]
        [Xunit.TraitAttribute("FeatureTitle", "producer")]
        [Xunit.TraitAttribute("Description", "Delete the producer using id")]
        [Xunit.TraitAttribute("Category", "deleteproducer")]
        [Xunit.InlineDataAttribute("producers/DeleteProducer/1", "200", "deleted successfully", new string[0])]
        [Xunit.InlineDataAttribute("producers/DeleteProducer/-1", "400", "invalid Arguments", new string[0])]
        [Xunit.InlineDataAttribute("producers/DeleteProducer/0", "400", "invalid Arguments", new string[0])]
        [Xunit.InlineDataAttribute("producers/DeleteProducer/100", "404", "No Content Found", new string[0])]
        public virtual void DeleteTheProducerUsingId(string resourceEndpoint, string statusCode, string responseData, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "deleteproducer"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("resourceEndpoint", resourceEndpoint);
            argumentsOfScenario.Add("statusCode", statusCode);
            argumentsOfScenario.Add("responseData", responseData);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Delete the producer using id", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 42
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 43
         testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 44
         testRunner.When(string.Format("I make Delete Request \'{0}\'", resourceEndpoint), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 45
         testRunner.Then(string.Format("response code must be \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 46
         testRunner.And(string.Format("response data must look like \'{0}\'", responseData), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="update the producer using id")]
        [Xunit.TraitAttribute("FeatureTitle", "producer")]
        [Xunit.TraitAttribute("Description", "update the producer using id")]
        [Xunit.TraitAttribute("Category", "updateproducer")]
        [Xunit.InlineDataAttribute("{\"name\":\"jerry Christopher\",\"bio\":\"jerryBio\",\"dob\":\"2001-12-02T00:00:00\",\"gender\"" +
            ":\"male\"}", "producers/UpdateProducer/1", "200", "updated successfully", new string[0])]
        [Xunit.InlineDataAttribute("{\"name\":\"\",\"bio\":\"jerryBio\",\"dob\":\"2001-12-02T00:00:00\",\"gender\":\"male\"}", "producers/UpdateProducer/1", "400", "invalid Arguments", new string[0])]
        [Xunit.InlineDataAttribute("{\"name\":\"jerry Christopher\",\"bio\":\"\",\"dob\":\"2001-12-02T00:00:00\",\"gender\":\"male\"}" +
            "", "producers/UpdateProducer/1", "400", "invalid Arguments", new string[0])]
        [Xunit.InlineDataAttribute("{\"name\":\"jerry Christopher\",\"bio\":\"jerryBio\",\"dob\":\"2001-12-02T00:00:00\",\"gender\"" +
            ":\"\"}", "producers/UpdateProducer/1", "400", "invalid Arguments", new string[0])]
        [Xunit.InlineDataAttribute("{\"name\":\"jerry Christopher\",\"bio\":\"jerryBio\",\"dob\":\"2001-12-02T00:00:00\",\"gender\"" +
            ":\"male\"}", "producers/UpdateProducer/-1", "400", "invalid Arguments", new string[0])]
        [Xunit.InlineDataAttribute("{\"name\":\"jerry Christopher\",\"bio\":\"jerryBio\",\"dob\":\"2001-12-02T00:00:00\",\"gender\"" +
            ":\"male\"}", "producers/UpdateProducer/100", "404", "No Content Found", new string[0])]
        public virtual void UpdateTheProducerUsingId(string data, string resourceEndpoint, string statusCode, string responseData, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "updateproducer"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Data", data);
            argumentsOfScenario.Add("resourceEndpoint", resourceEndpoint);
            argumentsOfScenario.Add("statusCode", statusCode);
            argumentsOfScenario.Add("responseData", responseData);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("update the producer using id", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 56
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 57
          testRunner.Given("I am a client", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 58
          testRunner.When(string.Format("I make PUT Request \'{0}\' with the following Data with the following Data \'{1}\'", resourceEndpoint, data), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 59
          testRunner.Then(string.Format("response code must be \'{0}\'", statusCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 60
          testRunner.And(string.Format("response data must look like \'{0}\'", responseData), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ProducerFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ProducerFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
